universe = container
docker_image = docker://marissazhang/python_perl_saml_popoo:1.0

transfer_input_files = popoolationStats.sh, popoolationStats_na_KL.py, MtbNCBIH37Rv.fa, RNAseq_31.zip 
executable = popoolationStats.sh

log = popoolationStat$(Cluster)_$(Process).log
output = popoolationStat$(Cluster)_$(Process).out
error = popoolationStat$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 25GB
request_disk = 110GB

queue
